### ISSUE TITLE
Any KD experimental results that can be published?

### ISSUE THREAD

**Issue by moyans** [Senwang98/Lightweight-Detection-and-KD#1]

**Comment by Senwang98** [comment]
@moyans 
Thanks for your interest. which checkpoints do you want? 
I have enough GPUs current. This week I will update some of these checkpoints (feel sorry, because I hace no access to previous ckpts now).

**Comment by moyans** [comment]
Thank you for your work. 
I'm just interested in the performance of distillation on lightweight models.

**Comment by Senwang98** [comment]
@moyans 
Sorry, I haven't distilled the lightweight detection network before.

I remember that the authors of FGD and CWD said in the previous wechat group that distillation technology will not greatly improve the lightweight network, and there is a distillation upper limit for small networks.

Take `YOLOX-Tiny` as an example, distillation can achieve little performance improvement, because these networks are well designed by hand, and there is no distillation space left.

That is why recent KD papers don't show lightweight detection model's performance.

**Comment by moyans** [comment]
Thank you for your patience
